### ISSUE TITLE
Add an option to specify the replit-3B-inference repo.

### ISSUE THREAD

**Issue by edelreal** [GPT-do-dah/Replit-Container#1]
It would be nice to have an option to specify a different git repo, or a local filesystem path to a local modified replit-3B-inference repo.

**Comment by StarKeyJON** [comment]
Let me see what I can do after work!

**Comment by StarKeyJON** [comment]
I added a command line arg option to pass in a custom repo or a local filesystem path to the docker container build. If one is not provided, it will default to the original.
